services:
  _defaults:
    autowire: true
    autoconfigure: true

  SCA\Rules\:
    resource: '../../*'
    exclude: '../../{DependencyInjection,Resources}'
  SCA\Rules\Entity\Rule: ~
  SCA\Rules\Repository\RuleRepository:
    factory: ['@doctrine', getRepository]
    arguments:
      - Rules\Entity\Rule
  SCA\Rules\Domain\Rule\RulesRegistry:
    public: true